---
apiVersion: installation.mattermost.com/v1beta1
kind: Mattermost
metadata:
  name: {{ .Values.name }}
spec:
  image: {{ .Values.image }}
  size: {{ .Values.size }}
  ingress:
    enabled: true
    host: {{ .Values.host }}
    annotations:
      kubernetes.io/ingress.class: nginx
  mattermostEnv:
    - name: "MM_SERVICESETTINGS_ALLOWCORSFROM"
      value: {{ printf "%s%s" "http://" .Values.host }}
    - name: MM_FILESETTINGS_AMAZONS3SSL
      value: "false"
  version: {{ .Values.version }}
  database:
    external:
      secret: {{ .Values.database_secret }}
  fileStore:
    external:
      bucket: {{ .Values.bucket }}
      url: {{ .Values.fileStore_url }}
      secret: {{ .Values.bucket_secret }}
